[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'wadackel/vim-dogrun'

# [[plugins]]
# repo = 'taigacute/gruvbox9'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
if = 'has("nvim")'
# dayfoxの色が変わりすぎているので古いバージョンで固定
rev = 'v2.1.0'
