[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'wadackel/vim-dogrun'

# [[plugins]]
# repo = 'taigacute/gruvbox9'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'
if = 'has("nvim")'
# lua_source = {{{
lua_source = '''
require("nightfox").setup()
'''
# }}}
