[[plugins]]
repo = 'Shougo/ddu.vim'
depends = ['denops.vim']
on_source = 'denops.vim'
# hook_add {{{
hook_add = '''
"nnoremap <silent> <C-u><C-p> :call ddu#start()<CR>
nnoremap <silent> <C-u><C-p> :call ddu#start({'name': 'rg-file_rec'})<CR>
nnoremap <silent> <C-u><C-g> :call ddu#start({'name': 'grep'})<CR>
nnoremap <silent> <C-u><C-]> :call ddu#start({'name': 'cursor-grep', 'sources': [{'name': 'rg', 'params': {'input': expand('<cword>')}}]})<CR>
nnoremap <silent> <C-u><C-m> :call ddu#start({'name': 'filer'})<CR>

'''
# }}}
# hook_source {{{
hook_source = '''
call ddu#custom#patch_global({
    \   'ui': 'ff',
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': ['matcher_substring'],
    \     },
    \     'file_rec': {
    \       'matchers': [
    \         'matcher_substring', 'matcher_hidden'
    \       ]
    \     },
    \   },
    \   'kindOptions': {
    \     'file': {
    \       'defaultAction': 'open',
    \     },
    \   },
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:true,
    \       'split': 'floating',
    \       'filterSplitDirection': 'floating',
    \       'filterFloatingPosition': 'bottom',
    \       'floatingBorder': ['╭', '─', '╮', '│', '╯', '─', '╰', '│'],
    \       'previewFloating': v:true,
    \       'prompt': '❯ ',
    \       'displaySourceName': 'short'
    \     },
    \   },
    \ })

call ddu#custom#patch_local('filer', {
    \   'ui': 'filer',
    \   'sources': [
    \     {'name': 'file'}
    \   ],
    \   'uiParams': {
    \     'filer': {
    \       'split': 'floating',
    \       'previewFloating': v:true,
    \     },
    \   },
    \   'actionOptions': {
    \     'narrow': {
    \       'quit': v:false,
    \     },
    \   },
    \ })

" ripgrepでfile_rec
call ddu#custom#patch_local('rg-file_rec', {
    \   'sources': [
    \     {'name': 'file_external'}
    \   ],
    \   'sourceParams': {
    \     'file_external': {
    \       'cmd': ['rg', '--threads', '4', '--files', '--column', '--no-heading', '--color', 'never', '--glob', '!.git'],
    \     },
    \   },
    \ })

call ddu#custom#patch_local('grep', {
    \   'volatile': v:true,
    \   'uiParams': {
    \     'ff': {
    \       'ignoreEmpty': v:false,
    \       'autoResize': v:false,
    \     },
    \   },
    \   'sources': [{'name': 'rg'}],
    \   'sourceParams': {
    \     'rg': {
    \       'args': ['--threads', '4', '--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \   'sourceOptions': {
    \     '_': {
    \       'matchers': [],
    \     },
    \   },
    \ })

call ddu#custom#patch_local('cursor-grep', {
    \   'uiParams': {
    \     'ff': {
    \       'startFilter': v:false,
    \       'ignoreEmpty': v:false,
    \       'autoResize': v:false,
    \     },
    \   },
    \   'sources': [{'name': 'rg'}],
    \   'sourceParams': {
    \     'rg': {
    \       'args': ['--threads', '4', '--column', '--no-heading', '--color', 'never', '--json'],
    \     },
    \   },
    \ })


autocmd FileType ddu-ff call s:ddu_my_settings()
function! s:ddu_my_settings() abort
  nnoremap <buffer><silent> <CR>
        \ <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
  nnoremap <buffer><silent> <Space>
        \ <Cmd>call ddu#ui#ff#do_action('toggleSelectItem')<CR>
  nnoremap <buffer><silent> i
        \ <Cmd>call ddu#ui#ff#do_action('openFilterWindow')<CR>
  nnoremap <buffer><silent> <ESC>
        \ <Cmd>call ddu#ui#ff#do_action('quit')<CR>
  nnoremap <buffer><silent> p
        \ <Cmd>call ddu#ui#ff#do_action('preview')<CR>
endfunction

autocmd FileType ddu-ff-filter call s:ddu_filter_my_settings()
function! s:ddu_filter_my_settings() abort
  inoremap <buffer><silent> <CR>
  \ <Esc><Cmd>close<CR>
  nnoremap <buffer><silent> <CR>
  \ <Cmd>close<CR>
  nnoremap <buffer><silent> <ESC>
  \ <Cmd>close<CR>
endfunction

autocmd FileType ddu-filer call s:ddu_filer_my_settings()
function! s:ddu_filer_my_settings() abort
  nnoremap <buffer><expr> <CR>
        \ ddu#ui#filer#is_directory() ?
        \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'narrow'})<CR>" :
        \ "<Cmd>call ddu#ui#filer#do_action('itemAction', {'name': 'open'})<CR>"
  nnoremap <buffer><silent> <ESC>
        \ <Cmd>quit<CR>
endfunction
'''
# }}}

[[plugins]]
repo = 'Shougo/ddu-commands.vim'
on_source = 'ddu.vim'
on_cmd = 'Ddu'

[[plugins]]
repo = 'Shougo/ddu-ui-ff'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-ui-filer'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-kind-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_substring'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-source-file_rec'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-matcher_hidden'
on_source = 'ddu.vim'

[[plugins]]
repo = 'shun/ddu-source-rg'
on_source = 'ddu.vim'

[[plugins]]
repo = 'Shougo/ddu-filter-converter_display_word'
on_source = 'ddu.vim'

[[plugins]]
repo = 'matsui54/ddu-source-file_external'
on_source = 'ddu.vim'
