[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# hook_add {{{
hook_add = """
let g:DevIconsEnableDistro = v:false
"""
# }}}

[[plugins]]
repo = 'halkn/lightline-lsp'

[[plugins]]
repo = 'yasunori-kirin0418/lightline_skk.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
# hook_add {{{
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'dayfox',
      \ 'active': {
      \   'left': [
      \     ['mode', 'paste', 'skk_mode'],
      \     ['filetype', 'filename', 'fugitive', 'gitgutter'],
      \     ['lsp_errors', 'lsp_warnings'],
      \   ],
      \   'right': [
      \     ['lineinfo', 'percent'],
      \     ['charcode', 'fileencoding', 'fileformaticon'],
      \   ]
      \ },
      \ 'inactive': {
      \   'left': [
      \     ['filename']
      \   ],
      \   'right':[
      \     ['fileformaticon'],
      \     ['charcode', 'fileencoding'],
      \   ]
      \ },
      \ 'tabline': {
      \   'left': [
      \     ['tabs'],
      \   ],
      \   'right': [
      \     ['duck_icon']
      \   ]
      \ },
      \ 'tab': {
      \   'active': ['tabnum', 'filename', 'modified'],
      \   'inactive': ['tabnum']
      \ },
      \ 'tab_component_function': {
      \   'modified': 'lightline#tab#modified',
      \   'readonly': 'lightline#tab#readonly',
      \   'tabnum': 'lightline#tab#tabnum',
      \   'fileicon': 'WebDevIconsGetFileTypeSymbol'
      \ },
      \ 'component': {
      \   'lambda_icon': 'ﬦ',
      \   'duck_icon': '',
      \   'vim_icon': '',
      \ },
      \ 'component_function': {
      \   'modified': 'MyModified',
      \   'readonly': 'MyReadonly',
      \   'fugitive': 'MyFugitive',
      \   'filename': 'MyFilename',
      \   'fileicon': 'WebDevIconsGetFileTypeSymbol',
      \   'fileformaticon': 'WebDevIconsGetFileFormatSymbol',
      \   'fileformat': 'MyFileformat',
      \   'filetype': 'MyFiletype',
      \   'fileencoding': 'MyFileencoding',
      \   'mode': 'MyMode',
      \   'syntastic': 'SyntasticStatuslineFlag',
      \   'charcode': 'MyCharCode',
      \   'gitgutter': 'MyGitGutter',
      \   'cocstatus': 'MyCocStatus',
      \   'lsp_errors': 'lightline_lsp#errors',
      \   'lsp_warnings': 'lightilne_lsp#warnings',
      \   'skk_mode': 'g:lightline_skk#mode',
      \ },
      \ 'separator': {'left': '', 'right': ''},
      \ 'subseparator': {'left': '', 'right': ''}
      \ }


function! s:trim(str)
  if exists('*trim')
    return trim(a:str)
  endif
  return substitute(a:str, '\s\+$', '', '')
endfunction

function! MyTabFileName(n) abort
  let buflist = tabpagebuflist(a:n)
  let winnr = tabpagewinnr(a:n)

  let filename_local = expand('#' . buflist[winnr - 1] . ':t')
  let filename_full = expand('#' . buflist[winnr - 1] . ':p')

  return WebDevIconsGetFileTypeSymbol(filename_full) . ' ' . (filename_local !=# '' ? filename_local : '[No Name]')
endfunction

function! MyCocStatus() abort
  let info = get(b:, 'coc_diagnostic_info', {})
  let msgs = []
  if get(info, 'error', 0)
    call add(msgs, "\uf05e " . info['error'])
  endif
  if get(info, 'warning', 0)
    call add(msgs, "\uf525 " . info['warning'])
  endif
  return s:trim(join(msgs, ' ') . ' ' . get(g:, 'coc_status', ''))
endfunction

function! MyFileicon()
  return WebDevIconsGetFileTypeSymbol()
endfunction

function! MyGetLineInfo()
  if winwidth(0) <= 60
    return ""
  endif
  " return printf("\ue0a1 %3d:%-3d", line('.'), col('.'))
  return printf("%3d:%-3d \uf77a %3d%%", line('.'), col('.'), 100 * line('.') / line('$'))
endfunction

function! MyModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! MyReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &ro ? "\ue0a2" : ''
endfunction

function! MyFilename()
  if winwidth(0) <= 45
    return ""
  endif

  return expand('%:t') != '' ? expand('%:t') : '[No Name]'
endfunction

function! MyFugitive()
  if winwidth(0) <= 120
    return ""
  endif

  try
    if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
      let _ = fugitive#head()
      return strlen(_) ? "\ue0a0 "._ : ''
      " return strlen(_) ? "\ue702 "._ : ''
    endif
  catch
  endtry
  return ''
endfunction

function! MyFileformat()
  return winwidth(0) > 100 ? (&fileformat . ' ' . WebDevIconsGetFileFormatSymbol()) : ''
endfunction

function! MyFiletype()
  return winwidth(0) > 100 ? (strlen(&filetype) ?  WebDevIconsGetFileTypeSymbol() . ' ' . &filetype : '') : ''
endfunction

function! MyFileencoding()
  return winwidth(0) > 100 ? (strlen(&fenc) ? &fenc : &enc) : ''
endfunction

function! MyMode()
  return &ft == 'unite' ? 'Unite' :
        \ &ft == 'nerdtree' ? 'NERDTree' :
        \ &ft == 'ddu' ? 'Defx' :
        \ &ft == 'deol' ? 'Deol' :
        \ lightline#mode()
endfunction

function! MyGitGutter()
  if ! exists('*GitGutterGetHunkSummary')
        \ || ! get(g:, 'gitgutter_enabled', 0)
        \ || winwidth(0) <= 120
    return ''
  endif
  let symbols = [
        \ g:gitgutter_sign_added . ' ',
        \ g:gitgutter_sign_modified . ' ',
        \ g:gitgutter_sign_removed . ' '
        \ ]
  let hunks = GitGutterGetHunkSummary()
  let ret = []
  for i in [0, 1, 2]
    if hunks[i] > 0
      call add(ret, symbols[i] . hunks[i])
    endif
  endfor
  return join(ret, ' ')
endfunction

" https://github.com/Lokaltog/vim-powerline/blob/develop/autoload/Powerline/Functions.vim
function! MyCharCode()
  if winwidth(0) <= 120
    return ''
  endif

  " Get the output of :ascii
  redir => ascii
  silent! ascii
  redir END

  if match(ascii, 'NUL') != -1
    return 'NUL'
  endif

  " Zero pad hex values
  let nrformat = '0x%02x'

  let encoding = (&fenc == '' ? &enc : &fenc)

  if encoding == 'utf-8'
    " Zero pad with 4 zeroes in unicode files
    let nrformat = '0x%04x'
  endif

  " Get the character and the numeric value from the return value of :ascii
  " This matches the two first pieces of the return value, e.g.
  " "<F>  70" => char: 'F', nr: '70'
  let [str, char, nr; rest] = matchlist(ascii, '\v\<(.{-1,})\>\s*([0-9]+)')

  " Format the numeric value
  let nr = printf(nrformat, nr)

  return "'". char ."' ". nr
endfunction
'''
# }}}

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
# hook_add {{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
      \ '~/.config/nvim/template'
      \]
'''
# }}}

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
# hook_add {{{
hook_add = '''
let g:precious_enable_switchers = {
      \ 'javascript': {
      \   'setfiletype': 0
      \ }
      \ }
'''
# }}}

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
# hook_add {{{
hook_add = '''
let g:better_whitespace_filetypes_blacklist=['diff', 'gitcommit', 'denite', 'defx', 'help']
'''
# }}}

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'RRethy/vim-hexokinase'
build = 'make hexokinase'
# hook_add {{{
hook_add = '''
let g:Hexokinase_highlighters = ['backgroundfull']
'''
# }}}

[[plugins]]
repo = 'luochen1990/rainbow'
# hook_add {{{
hook_add = '''
let g:rainbow_active = 1
let g:rainbow_conf = {
\  'separately': {
\    'sml': {
\      'parentheses': ['start=/(\ze[^*]/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold']
\  }}
\}
'''
# }}}

[[plugins]]
repo = 'thinca/vim-quickrun'
# hook_add {{{
hook_add = '''
let g:quickrun_config = get(g:, 'quickrun_config', {})
let g:quickrun_no_default_key_mappings=1

let g:quickrun_config._ = {
      \ 'runner': 'nvimterm',
      \ 'runner/nvimterm/into': 1
      \ }

let g:quickrun_config.d = {
      \ 'command': 'dmd',
      \ 'cmdopt': '-run'
      \ }

let g:quickrun_config.cpp = {
      \ 'command': 'g++',
      \ 'cmdopt': '-std=c++2a -O3'
      \ }

let g:quickrun_config.scheme = {
      \ 'command': 'scheme',
      \ 'exec': '%c %o < %s',
      \ 'cmdopt': '--quiet'
      \ }

nnoremap <silent> <C-b> <Cmd>QuickRun<CR> i
'''
# }}}

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'
if = 'has("nvim")'

# vim-fakeclipはxclip無いとneovimが死ぬ
[[plugins]]
repo = 'kurokoji/vim-fakeclip'
# hook_add {{{
hook_add = '''
vnoremap <silent> <C-y> <Plug>(fakeclip-y)
'''
# }}}

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
if = 'has("nvim")'

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
if = '0'
# hook_add {{{
hook_add = '''
lua << EOF
require('lualine').setup {
  options = {
    icons_enabled = true,
    theme = 'auto',
    component_separators = { left = '', right = ''},
    section_separators = { left = '', right = ''},
    disabled_filetypes = {},
    always_divide_middle = true,
    globalstatus = false,
  },
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'filetype', 'filename'},
    lualine_c = {'branch', 'diff', {
      'diagnostics',
      sources = { 'vim_lsp' }
    }},
    lualine_x = {'encoding', 'fileformat'},
    lualine_y = {'location'},
    lualine_z = {'progress'}
  },
  inactive_sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = {'filename'},
    lualine_x = {'location'},
    lualine_y = {},
    lualine_z = {}
  },
  tabline = {
    lualine_a = {'tabs', 'filename'},
    lualine_b = {},
    lualine_c = {},
    lualine_x = {},
    lualine_y = {},
    lualine_z = {}
  },
  extensions = {}
}
EOF
'''
# }}}

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['vim-lsp-settings']
# hook_add {{{
hook_add = '''
let g:lsp_diagnostics_signs_warning = { 'text': "\uf525" }
let g:lsp_diagnostics_signs_error = { 'text': "\uf05e" }

if executable('bq-language-server')
  au User lsp_setup call lsp#register_server({
        \ 'name': 'bq-language-server',
        \ 'cmd': {server_info->['bq-language-server', '--stdio']},
        \ 'config': {
        \   "bqExtensionVSCode": {
        \     "diagnostic": {
        \       "forVSCode": v:false,
        \     }
        \   }
        \ },
        \ 'allowlist': ['sql', 'bigquery'],
        \ })
endif

function! s:on_lsp_buffer_enabled() abort
  setlocal signcolumn=yes

  nmap <silent> <Leader>rn <Plug>(lsp-rename)
  nmap <silent> <Leader>h <Plug>(lsp-hover)
  nmap <silent> <Leader>ca <Plug>(lsp-code-action)
  nmap <silent> gd <Plug>(lsp-definition)
  nmap <silent> gy <Plug>(lsp-type-definition)
  nmap <silent> gi <Plug>(lsp-implementation)
  nmap <silent> gr <Plug>(lsp-references)
  nmap <silent> F <Plug>(lsp-document-format)
  vmap <silent> F <Plug>(lsp-document-range-format)
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END
'''
# }}}

[[plugins]]
repo = 'mattn/vim-lsp-settings'
