[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'qnighy/satysfi.vim'
on_ft = 'saty'

[[plugins]]
repo = 'sulami/diet.vim'
on_ft = 'diet'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
# hook_add {{{
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''
# }}}

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Shougo/neco-syntax'
on_ft = ['vim']

[[plugins]]
repo = 'mityu/vim-applescript'
on_ft = ['applescript']

[[plugins]]
repo = 'PProvost/vim-ps1'

[[plugins]]
repo = 'reasonml-editor/vim-reason-plus'
