[[plugins]]
repo = 'icymind/NeoSolarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'squarefrog/tomorrow-night.vim'

[[plugins]]
repo = 'challenger-deep-theme/vim'

[[plugins]]
repo = 'sickill/vim-monokai'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Erichain/vim-monokai-pro'

[[plugins]]
repo = 'joshdick/onedark.vim'
