[[plugins]]
repo = 'icymind/NeoSolarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'chriskempson/tomorrow-theme'

[[plugins]]
repo = 'challenger-deep-theme/vim'
