[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = ['VimEnter']
hooks_file = '$LAZY_TOML_DIR/hooks_file/ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-previewer-floating'
on_source = 'ddc.vim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/ddc-previewer-floating.lua'

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/pum.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = 'pum.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_source = 'ddc.vim'
depends = ['neosnippet-snippets']
hooks_file = '$LAZY_TOML_DIR/hooks_file/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'Shougo/neco-vim'
# on_ft = ['vim', 'toml', 'markdown']
on_ft = ['vim']
on_event = ['CmdlineChanged']
depends = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
if = '0'
on_source = 'ddc.vim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/skkeleton.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'uga-rosa/ddc-nvim-lsp-setup'
on_source = 'ddc.source-nvim-lsp'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-copilot'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-input'
on_source = 'ddc.vim'
