[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_source = '''
let g:denops_server_addr = '127.0.0.1:32123'

" If you use dein.vim, you can get the path via `dein#get('denops.vim').path`.
" Or if you are a user of jetpack.vim, you can use `jetpack#get('denops.vim').path`.
let s:denops_path = dein#get('denops.vim').path
if has('nvim')
    call jobstart(
    \	'deno run -A --no-check ' . s:denops_path . '/denops/@denops-private/cli.ts',
    \	{'detach': v:true}
    \)
else
    call job_start(
    \   'deno run -A --no-check ' . s:denops_path . '/denops/@denops-private/cli.ts',
    \   {'stoponexit': ''}
    \)
endif
'''

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'
on_source = 'denops.vim'
hook_post_update = 'call denops_shared_server#install()'
