[[plugins]]
repo = 'vim-denops/denops.vim'
on_event = 'CursorHold'
hook_source = '''
let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'
on_source = 'denops.vim'
hook_post_update = 'call denops_shared_server#install()'
