[[plugins]]
repo = 'Shougo/deol.nvim'
on_event = ['VimEnter']
hooks_file = '$LAZY_TOML_DIR/hooks_file/deol.vim'

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
# hook_add {{{
hook_add = '''
let g:previm_enable_realtime = 1
augroup PrevimSettings
  autocmd!
  autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
augroup END
'''
# }}}

[[plugins]]
repo = 'tpope/vim-surround'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim") && !has("win32")'
on_event = ['BufRead', 'CursorHold']
# on_event = ['FileType']
on_ft = ['help']
hook_post_update = 'TSUpdate'
hooks_file = '$LAZY_TOML_DIR/hooks_file/nvim-treesitter.lua'

[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
if = 'has("nvim")'
# on_source = ['nvim-treesitter']
on_event = ['BufRead', 'BufNewFile']
# lua_source {{{
lua_source = '''
vim.opt.list = true
-- vim.opt.listchars:append("eol:↵")

require('ibl').setup()
'''
# }}}

[[plugins]]
repo = 'windwp/nvim-ts-autotag'
if = 'has("nvim")'
on_source = 'nvim-treesitter'
hooks_file = '$LAZY_TOML_DIR/hooks_file/nvim-ts-autotag.lua'

[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = ['BufRead', 'BufNewFile']
# lua_source {{{
lua_source = '''
require('gitsigns').setup()
'''
# }}}

[[plugins]]
repo = 'windwp/nvim-autopairs'
on_event = ['BufRead', 'BufNewFile']
# lua_source {{{
lua_source = '''
require("nvim-autopairs").setup {}
'''
# }}}

[[plugins]]
repo = 'NvChad/nvim-colorizer.lua'
on_event = ['BufRead', 'BufNewFile']
# lua_source {{{
lua_source = '''
require('colorizer').setup()
'''
# }}}

[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
on_event = ['UiEnter']
hooks_file = '$LAZY_TOML_DIR/hooks_file/lualine.lua'

[[plugins]]
repo = 'github/copilot.vim'
on_event = ['BufRead', 'BufNewFile']
# hook_add {{{
hook_add = '''
let g:copilot_no_tab_map = v:true
let g:copilot_filetypes = {
  \ 'ddu-ff': v:false,
  \ 'ddu-ff-filter': v:false,
  \ }
let g:copilot_hide_during_completion = 0
'''
# }}}

[[plugins]]
repo = 'petertriho/nvim-scrollbar'
on_event = ['BufRead', 'BufNewFile']
# lua_source {{{
lua_source = '''
require('scrollbar').setup({
  excluded_buftypes = { "terminal", "nofile" }
})
'''
# }}}

[[plugins]]
repo = 'itchyny/lightline.vim'
if = '0'
on_event = ['UiEnter']
hooks_file = '$LAZY_TOML_DIR/hooks_file/lightline.lua'

[[plugins]]
repo = 'klen/nvim-config-local'
if = '0'
on_event = ['VimEnter']
# lua_source {{{
lua_source = '''
require('config-local').setup {}
'''
# }}}
