[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'mason-lspconfig.nvim'
hooks_file = ['$LAZY_TOML_DIR/hooks_file/nvim-lspconfig.lua', '$LAZY_TOML_DIR/hooks_file/nvim-lspconfig.vim']

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'mason-lspconfig.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/mason.lua'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
depends = ['mason.nvim', 'nvim-lspconfig']
on_source = 'mason-null-ls.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/mason-lspconfig.lua'

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
# on_source = 'mason.nvim'
on_event = ['BufRead', 'BufNewFile']

[[plugins]]
repo = 'jayp0521/mason-null-ls.nvim'
on_source = 'none-ls.nvim'
# lua_source {{{
lua_source = '''

local null_ls = require('null-ls')
null_ls.setup()

require('mason-null-ls').setup({
  ensure_installed = { 'prettier', 'stylua', 'black' },
  automatic_setup = true,
  handlers = {}
})


'''
# }}}

[[plugins]]
repo = 'ErichDonGubler/lsp_lines.nvim'
if = '0'
on_source = 'nvim-lspconfig'
# lua_source {{{
lua_source = '''
require('lsp_lines').setup {}
'''
# }}}
