[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_source = 'mason-lspconfig.nvim'
on_event = ['FileType']

[[plugins]]
repo = 'mason-org/mason.nvim'
on_source = 'mason-lspconfig.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/mason.lua'

[[plugins]]
repo = 'mason-org/mason-lspconfig.nvim'
depends = ['mason.nvim', 'nvim-lspconfig']
on_source = 'mason-null-ls.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/mason-lspconfig.lua'

[[plugins]]
repo = 'nvimtools/none-ls.nvim'
on_event = ['FileType']
hooks_file = '$LAZY_TOML_DIR/hooks_file/none-ls.lua'

[[plugins]]
repo = 'jayp0521/mason-null-ls.nvim'
depends = ['mason.nvim', 'none-ls.nvim']
on_source = 'none-ls.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/mason-null-ls.lua'

[[plugins]]
repo = 'rachartier/tiny-inline-diagnostic.nvim'
on_source = 'mason-lspconfig.nvim'
hooks_file = '$LAZY_TOML_DIR/hooks_file/tiny-inline-diagnostic.lua'
