# [[plugins]]
# repo = 'Shougo/vimproc.vim'
# build = 'make'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
# hook_add {{{
hook_add = """
let g:DevIconsEnableDistro = v:false
"""
# }}}

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'mattn/vim-sonictemplate'
# hook_add {{{
hook_add = '''
let g:sonictemplate_vim_template_dir = [
      \ expand('$BASE_DIR/templates')
      \]
'''
# }}}

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
if = '0'

[[plugins]]
repo = 'osyo-manga/vim-precious'
if = '0'
depends = ['context_filetype.vim']
# hook_add {{{
hook_add = '''
let g:precious_enable_switchers = {
  \ 'javascript': {
  \   'setfiletype': 0
  \ }
  \ }
'''
# }}}

[[plugins]]
repo = 'ntpeters/vim-better-whitespace'
# hook_add {{{
hook_add = '''
let g:better_whitespace_filetypes_blacklist=['diff', 'gitcommit', 'denite', 'defx', 'help']
'''
# }}}

[[plugins]]
repo = 'luochen1990/rainbow'
# hook_add {{{
hook_add = '''
let g:rainbow_active = 1
let g:rainbow_conf = {
\  'separately': {
\    'sml': {
\      'parentheses': ['start=/(\ze[^*]/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold']
\  }}
\}
'''
# }}}

[[plugins]]
repo = 'thinca/vim-quickrun'
hooks_file = '$NORMAL_TOML_DIR/hooks_file/vim-quickrun.vim'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'
if = 'has("nvim")'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
if = 'has("nvim")'

[[plugins]]
repo = 'skanehira/denops-docker.vim'

[[plugins]]
repo = 'rcarriga/nvim-notify'
hooks_file = '$NORMAL_TOML_DIR/hooks_file/nvim-notify.lua'
